// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tour.proto

package proto

import (
	context "context"
	errors "errors"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetTagListRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State                uint32   `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTagListRequest) Reset()         { *m = GetTagListRequest{} }
func (m *GetTagListRequest) String() string { return proto.CompactTextString(m) }
func (*GetTagListRequest) ProtoMessage()    {}
func (*GetTagListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b8a0da1d14bccfa, []int{0}
}

func (m *GetTagListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTagListRequest.Unmarshal(m, b)
}
func (m *GetTagListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTagListRequest.Marshal(b, m, deterministic)
}
func (m *GetTagListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTagListRequest.Merge(m, src)
}
func (m *GetTagListRequest) XXX_Size() int {
	return xxx_messageInfo_GetTagListRequest.Size(m)
}
func (m *GetTagListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTagListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTagListRequest proto.InternalMessageInfo

func (m *GetTagListRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetTagListRequest) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

type Tag struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State                uint32   `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b8a0da1d14bccfa, []int{1}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tag) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

type GetTagListResponse struct {
	List                 []*Tag   `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Pager                *Pager   `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTagListResponse) Reset()         { *m = GetTagListResponse{} }
func (m *GetTagListResponse) String() string { return proto.CompactTextString(m) }
func (*GetTagListResponse) ProtoMessage()    {}
func (*GetTagListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b8a0da1d14bccfa, []int{2}
}

func (m *GetTagListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTagListResponse.Unmarshal(m, b)
}
func (m *GetTagListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTagListResponse.Marshal(b, m, deterministic)
}
func (m *GetTagListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTagListResponse.Merge(m, src)
}
func (m *GetTagListResponse) XXX_Size() int {
	return xxx_messageInfo_GetTagListResponse.Size(m)
}
func (m *GetTagListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTagListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTagListResponse proto.InternalMessageInfo

func (m *GetTagListResponse) GetList() []*Tag {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *GetTagListResponse) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

func init() {
	proto.RegisterType((*GetTagListRequest)(nil), "proto.GetTagListRequest")
	proto.RegisterType((*Tag)(nil), "proto.Tag")
	proto.RegisterType((*GetTagListResponse)(nil), "proto.GetTagListResponse")
}

func init() { proto.RegisterFile("proto/tour.proto", fileDescriptor_1b8a0da1d14bccfa) }

var fileDescriptor_1b8a0da1d14bccfa = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4e, 0xf3, 0x30,
	0x10, 0x85, 0x95, 0xa4, 0xfd, 0xa5, 0x7f, 0x5a, 0x2a, 0x18, 0x75, 0x11, 0x2a, 0x84, 0xa2, 0xac,
	0xb2, 0x6a, 0x44, 0x58, 0x23, 0x96, 0x6c, 0x58, 0x20, 0x13, 0x09, 0xb6, 0x43, 0x3b, 0xb2, 0x2c,
	0x35, 0x76, 0x88, 0xa7, 0x3d, 0x00, 0x57, 0xe0, 0x68, 0x5c, 0x81, 0x83, 0x20, 0xec, 0x0a, 0x2a,
	0xd1, 0x95, 0xc7, 0xf3, 0x3d, 0xbf, 0x37, 0x1e, 0x38, 0xed, 0x07, 0x27, 0xae, 0x16, 0xb7, 0x1d,
	0x96, 0xa1, 0xc4, 0x71, 0x38, 0x16, 0x18, 0xc1, 0xca, 0x75, 0x9d, 0xb3, 0x11, 0x2d, 0x2e, 0xb4,
	0x73, 0x7a, 0xc3, 0x35, 0xf5, 0xa6, 0x26, 0x6b, 0x9d, 0x90, 0x18, 0x67, 0x7d, 0xa4, 0xe5, 0x0d,
	0x9c, 0xdd, 0xb1, 0xb4, 0xa4, 0xef, 0x8d, 0x17, 0xc5, 0xaf, 0x5b, 0xf6, 0x82, 0x08, 0x23, 0x4b,
	0x1d, 0xe7, 0x49, 0x91, 0x54, 0xff, 0x55, 0xa8, 0x71, 0x0e, 0x63, 0x2f, 0x24, 0x9c, 0xa7, 0x45,
	0x52, 0x9d, 0xa8, 0x78, 0x29, 0x6f, 0x21, 0x6b, 0x49, 0xe3, 0x0c, 0x52, 0xb3, 0x0e, 0xf2, 0x4c,
	0xa5, 0x66, 0xfd, 0x63, 0x90, 0x1e, 0x33, 0xc8, 0x0e, 0x0d, 0x9e, 0x01, 0x0f, 0xf3, 0x7d, 0xef,
	0xac, 0x67, 0xbc, 0x84, 0xd1, 0xc6, 0x78, 0xc9, 0x93, 0x22, 0xab, 0x26, 0x0d, 0xc4, 0x59, 0x97,
	0x2d, 0x69, 0x15, 0xfa, 0x58, 0xc2, 0xb8, 0x27, 0xcd, 0x43, 0x08, 0x98, 0x34, 0xd3, 0xbd, 0xe0,
	0xe1, 0xbb, 0xa7, 0x22, 0x6a, 0x18, 0xa0, 0x25, 0xfd, 0xc8, 0xc3, 0xce, 0xac, 0x18, 0x9f, 0x00,
	0x7e, 0x73, 0x30, 0xdf, 0x3f, 0xf8, 0xf3, 0xf5, 0xc5, 0xf9, 0x11, 0x12, 0x87, 0x2a, 0xe7, 0x6f,
	0x1f, 0x9f, 0xef, 0xe9, 0x0c, 0xa7, 0x61, 0x95, 0xbb, 0xab, 0x5a, 0x48, 0xfb, 0x97, 0x7f, 0x41,
	0x7f, 0xfd, 0x15, 0x00, 0x00, 0xff, 0xff, 0x81, 0xeb, 0x11, 0x4e, 0x94, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TagServiceClient is the client API for TagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TagServiceClient interface {
	GetTagList(ctx context.Context, in *GetTagListRequest, opts ...grpc.CallOption) (*GetTagListResponse, error)
	WithOrgCode(ctx context.Context, orgCode string) context.Context
}

type tagServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTagServiceClient(cc grpc.ClientConnInterface) TagServiceClient {
	return &tagServiceClient{cc}
}

type orgCodeKey struct{}

func (c *tagServiceClient) WithOrgCode(ctx context.Context, orgCode string) context.Context {
	return context.WithValue(ctx, orgCodeKey{}, orgCode)
}

func (c *tagServiceClient) OrgCode(ctx context.Context) string {
	return ctx.Value(orgCodeKey{}).(string)
}
func (c *tagServiceClient) GetTagList(ctx context.Context, in *GetTagListRequest, opts ...grpc.CallOption) (*GetTagListResponse, error) {
	orgCode, ok := c.OrgCode(ctx)
	if !ok || orgCode == "" {
		return nil, errors.New("请调用 WithOrgCode 方法设置租户标识")
	}
	out := new(GetTagListResponse)
	err := c.cc.Invoke(ctx, "/proto.TagService/GetTagList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TagServiceServer is the server API for TagService service.
type TagServiceServer interface {
	GetTagList(context.Context, *GetTagListRequest) (*GetTagListResponse, error)
}

// UnimplementedTagServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTagServiceServer struct {
}

func (*UnimplementedTagServiceServer) GetTagList(ctx context.Context, req *GetTagListRequest) (*GetTagListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTagList not implemented")
}

func RegisterTagServiceServer(s *grpc.Server, srv TagServiceServer) {
	s.RegisterService(&_TagService_serviceDesc, srv)
}

func _TagService_GetTagList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTagListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServiceServer).GetTagList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TagService/GetTagList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServiceServer).GetTagList(ctx, req.(*GetTagListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TagService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TagService",
	HandlerType: (*TagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTagList",
			Handler:    _TagService_GetTagList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tour.proto",
}
